#############################################################################
# Generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#  Nov 30, 2020 01:11:48 AM IST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #000000 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+713+322
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Image Processing"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #FDD700 \
        -font {-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #333333 -highlightcolor black -text D-Process 
    vTcl:DefineAlias "$top.lab45" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but51 \
        -activebackground #f9f9f9 -activeforeground black -background #FFD700 \
        -command rotate(img) -font TkDefaultFont -foreground #333333 \
        -highlightcolor black -text Rotate 
    vTcl:DefineAlias "$top.but51" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but55 \
        -activebackground #f9f9f9 -activeforeground black -background #FFD700 \
        -font denoise -foreground #333333 -highlightcolor black -text denoise 
    vTcl:DefineAlias "$top.but55" "Button2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent45 \
        -background #FFD700 -font TkFixedFont -foreground #333333 \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 56 
    vTcl:DefineAlias "$top.ent45" "ang" vTcl:WidgetProc "Toplevel1" 1
    button $top.but49 \
        -activebackground #f9f9f9 -activeforeground black -background #FFD700 \
        -font TkDefaultFont -foreground #333333 -highlightcolor black \
        -text Resize 
    vTcl:DefineAlias "$top.but49" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground #f9f9f9 -activeforeground black -background #FFD700 \
        -font TkDefaultFont -foreground #333333 -highlightcolor black \
        -text Upload 
    vTcl:DefineAlias "$top.but53" "Button5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent54 \
        -background #FFD700 -font TkFixedFont -foreground #333333 \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 156 
    vTcl:DefineAlias "$top.ent54" "img" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent55 \
        -background #FFD700 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 56 
    vTcl:DefineAlias "$top.ent55" "s1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent56 \
        -background #FFD700 -font TkFixedFont -foreground #333333 \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 66 
    vTcl:DefineAlias "$top.ent56" "s2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but57 \
        -activebackground #f9f9f9 -activeforeground black -background #FFD700 \
        -font TkDefaultFont -foreground #333333 -highlightcolor black \
        -text Exit 
    vTcl:DefineAlias "$top.but57" "Button4" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.044 -width 0 -relwidth 0.315 \
        -height 0 -relheight 0.113 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.444 -width 141 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.689 -width 141 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 0 -relx 0.383 -y 0 -rely 0.444 -width 56 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.578 -width 141 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.333 -width 141 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.383 -y 0 -rely 0.333 -width 156 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 0 -relx 0.383 -y 0 -rely 0.578 -width 56 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.5 -y 0 -rely 0.578 -width 56 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.911 -width 141 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

